name: ci 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    container: circleci/node:12.16-browsers
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Dependencies
      run: yarn
    - name: Test
      run: yarn test
    - name: Build
      run: yarn build
